[theme]
base="dark"
primaryColor="#ffffff"
backgroundColor="#0e0e10"
secondaryBackgroundColor="#1d1d21"
textColor="#ffffff"
font="sans serif"

[server]
maxUploadSize=200
maxMessageSize=100
enableCORS=false

[browser]
gatherUsageStats=false

[runner]
fastRerenderEnabled=false
magicEnabled=true

[logger]
level="warning"

[client]
toolbarMode="minimal"
showErrorDetails=false
# Ocultar la barra de progreso (l√≠nea naranja)

displayEnabled=false

[global]
dataFrameSerialization="arrow"

# Desactivar elementos de la interfaz de usuario
[ui]
hideTopBar=true  # Oculta la barra superior completa

